name: manifest-deploy

# You need to have the following secrets defined in this github repo: 
# DOCKER_USERNAME, DOCKER_PASSWORD, DIGITAL_OCEAN_ACCESS_TOKEN

on:
  push:
    branches:
      - main
    paths:
      - infrastructure/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- uses: digitalocean/action-doctl@v2
      #  with:
      #    token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
      - run: echo "Applying kubernetes manifest"
      #- run: doctl kubernetes cluster kubeconfig save YOUR_CLUSTER_NAME
      #- run: kubectl apply -f infrastructure/k8s
